version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/ai-business
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: Lbs990129...

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: Lbs990129...
      TZ: Asia/Shanghai
      LANG: C.UTF-8
    volumes:
      - /root/mysqlData:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password