CREATE TABLE IF NOT EXISTS user_table (
    id INT PRIMARY KEY AUTO_INCREMENT COMMENT '用户自增',
    userName VARCHAR(100) NOT NULL UNIQUE COMMENT '用户名称',
    password VARCHAR(100) NOT NULL COMMENT '用户密码',
    createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    INDEX idx_userName(userName)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户信息表';

ALTER TABLE user_table ADD createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间';
ALTER TABLE user_table ADD updateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间';
