spring.application.name=ai-work-flow-back

# 数据库配置
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://43.138.198.247:3306/ai-business?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Lbs990129...

# MyBatis-Plus 配置
mybatis-plus.type-aliases-package=com.example.aiworkflowback.*.Entity,com.example.aiworkflowback.common.Entity
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.mapper-locations=classpath:mapper/*.xml

# Redis 配置
spring.data.redis.host=43.138.198.247
spring.data.redis.port=6379
spring.data.redis.username=root
spring.data.redis.password=lbs990129
spring.data.redis.timeout=10000
spring.data.redis.database=0
spring.data.redis.lettuce.pool.max-active=8
spring.data.redis.lettuce.pool.max-idle=8
spring.data.redis.lettuce.pool.min-idle=0
spring.data.redis.lettuce.pool.max-wait=-1
