spring.application.name=ai-work-flow-back

# =====================  数据库配置 =====================
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://43.138.198.247:3306/ai-business?useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Lbs990129...

# ===================== MyBatis-Plus 配置 =====================
mybatis-plus.type-aliases-package=com.example.aiworkflowback.User.Model.Entity
mybatis-plus.configuration.map-underscore-to-camel-case=true
mybatis-plus.configuration.log-impl=org.apache.ibatis.logging.stdout.StdOutImpl
mybatis-plus.mapper-locations=classpath:mapper/*.xml