CREATE TABLE IF NOT EXISTS flow_info (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    userId INT NOT NULL COMMENT '用户id',
    userName VARCHAR(100) NOT NULL COMMENT '用户名称',
    appName VARCHAR(120) NOT NULL COMMENT '流程名称',
    appDesc VARCHAR(500) COMMENT '流程描述',
    appType VARCHAR(50) NOT NULL COMMENT '流程类型',
    flowConfigId INT NOT NULL COMMENT '流程id',
    createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    flowStatus INT NOT NULL COMMENT '流程状态 1 草稿， 2发布'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程表'

CREATE TABLE IF NOT EXISTS flow_config (
    flowConfigId BIGINT PRIMARY KEY COMMENT '流程配置id',
    nodeList JSON NOT NULL COMMENT '流程节点配置',
    edgeList JSON NOT NULL COMMENT '流程连接线配置',
    createTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    updateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='流程配置表'


ALTER TABLE flow_info MODIFY COLUMN flowConfigId BIGINT;