CREATE TABLE IF NOT EXISTS llm_config (
    id BIGINT PRIMARY KEY AUTO_INCREMENT COMMENT '主键',
    modalType VARCHAR(200) NOT NULL COMMENT '模型类型',
    apiKey VARCHAR(256) NOT NULL COMMENT '模型秘钥'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT '模型配置key';